### ISSUE TITLE
Exception with AdBlock Plus

### ISSUE THREAD

**Issue by sanishmistry** [isc30/blazor-analytics#55]
If AdBlock Plus is turned on with the 'Block Additional Tracking' option turned on (which blocks blazor-analytics.js),  it causes the circuit to crash so the website is no longer responsive. 

```
    blazor.server.js:1 [2022-10-08T19:16:12.354Z] Error: Microsoft.JSInterop.JSException: Could not find 'GoogleAnalyticsInterop.configure' ('GoogleAnalyticsInterop' was undefined).
        Error: Could not find 'GoogleAnalyticsInterop.configure' ('GoogleAnalyticsInterop' was undefined).
            at http://localhost:5015/_framework/blazor.server.js:1:497
            at Array.forEach (<anonymous>)
            at i.findFunction (http://localhost:5015/_framework/blazor.server.js:1:465)
            at E (http://localhost:5015/_framework/blazor.server.js:1:2606)
            at http://localhost:5015/_framework/blazor.server.js:1:3494
            at new Promise (<anonymous>)
            at kt.beginInvokeJSFromDotNet (http://localhost:5015/_framework/blazor.server.js:1:3475)
            at http://localhost:5015/_framework/blazor.server.js:1:72061
            at Array.forEach (<anonymous>)
            at kt._invokeClientMethod (http://localhost:5015/_framework/blazor.server.js:1:72047)
        at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
        at Blazor.Analytics.GoogleAnalytics.GoogleAnalyticsStrategy.Initialize(String trackingId)
        at Blazor.Analytics.GoogleAnalytics.GoogleAnalyticsStrategy.TrackNavigation(String uri)
        at Blazor.Analytics.Components.NavigationTracker.OnLocationChanged(String location)
        at Blazor.Analytics.Components.NavigationTracker.OnAfterRenderAsync(Boolean firstRender)
        at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by sanishmistry** [comment]
I've fixed it for now by adding a fake object if the blazor-analytics.js file gets blocked : 

`    <script src="_content/Blazor-Analytics/blazor-analytics.js"></script>
    <script>
        if(typeof window.GoogleAnalyticsInterop === 'undefined') {
            window.GoogleAnalyticsInterop = {
                debug : false,
                navigate(){},
                trackEvent(){},
                configure(){}
            };
        }
    </script>
`

**Comment by csharpfritz** [comment]
Nice workaround @sanishmistry !   I'd like to see the library fail silently if adblock is turned on.  I'll look at opening a PR to add this

**Comment by ssunny-lower** [comment]
Running into the same issue, thanks for the workaround @sanishmistry

**Comment by isc30** [comment]
Hey, good catch, it should be fairly simple to check if `GoogleAnalyticsInterop` is there before invoking the methods.
Happy to accept PRs with the change!

**Comment by Silvenga** [comment]
Just for documentation: https://github.com/easylist/easylist/issues/13846

I think the change should likely be made on both sides - but at the very least, any analytics library should handle being blocked.
